CREATE TABLE books (book_id serial PRIMARY KEY, author TEXT NOT NULL, title TEXT NOT NULL, year TEXT, publisher TEXT NOT NULL, language TEXT NOT NULL, genre TEXT, format TEXT, description TEXT, price INTEGER NOT NULL, home_page BOOLEAN NOT NULL, img TEXT NOT NULL);

CREATE TABLE cart (cart_id serial PRIMARY KEY, book_id INTEGER NOT NULL, FOREIGN KEY(book_id) REFERENCES books(book_id));

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price, home_page, img) VALUES ('Emil Larsson', 'Glödens skugga', '2021','Bäck Förlag', 'Svenska', 'Samtida könlitteratur', 'Pocket', 'När den introverta konstnären Lea återvänder till sin barndomsstad efter sin fars plötsliga död, möts hon av ett hus fyllt av osagda ord och mörka minnen. Bland hans ägodelar finner hon en samling brev adresserade till en kvinna hon aldrig hört talas om. Samtidigt börjar Leas tavlor ta en ny, mörkare form – bilder av en kvinna som tycks hemsöka hennes drömmar. Vem var kvinnan i breven, och varför vägrar hennes närvaro att släppa taget? I jakten på sanningen tvingas Lea konfrontera sin fars hemligheter och den glödande skuggan av sitt eget förflutna.', 99, FALSE, 'src/assets/IMG/glodens_skugga.png');

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price) VALUES ('Hanna Lindberg', 'Alltid din dotter', '2019', 'Förlaget Roman', 'Svenska', 'Samtida skönlitteratur', 'Pocket', 'När 32-åriga Nora återvänder hem för att ta hand om sin dementa mor, tvingas hon konfrontera både sin egen skuld och de oläkta såren från en barndom präglad av oförklarliga tystnader och brutna löften. Hennes mor växlar mellan klara stunder och fragmenterade minnen, och Nora börjar pussla ihop bitarna av ett liv hon aldrig riktigt känt till. Vem var hennes mor innan sjukdomen tog över? Och vad hände egentligen den där sommaren när Noras syster försvann spårlöst? Alltid din dotter är en gripande berättelse om svek, försoning och den smärtsamma insikten att vissa sanningar aldrig kan lämnas obegripliga.', 129);

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price) VALUES ('Emily Carter', 'Beneath the sunset', '2023', 'Space publishing', 'Engelska', 'Romantik', 'Pocket', 'After a devastating breakup, aspiring photographer Lila moves to a bustling city to start fresh. Amid the noise and chaos, she finds solace on the rooftop of her apartment building, where the sunset casts a warm glow over the skyline. It’s there she meets Aiden, a charming yet guarded bartender who seeks refuge from his past under the same evening sky. Night after night, their encounters deepen as they share secrets, laughter, and stolen glances against the backdrop of the city’s lights. But as Lila begins to uncover the truth behind Aiden’s haunted eyes, she must decide if she’s willing to risk her heart again.', 109);

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price) VALUES ('Astrid Skoog', 'Blommornas hemlighet', '1916', 'Lind Förlag', 'Svenska', 'Klassiker', 'Inbunden', 'När den unga, modiga Helena anländer till den avlägsna gården Älvkullen för att arbeta som piga, möts hon av bybornas viskningar om gårdens mörka förflutna. Det sägs att blommorna i den förvuxna trädgården bär på viskande hemligheter, berättelser om förbjuden kärlek, förlorade själar och löften som aldrig infriats. Helena dras till trädgårdens förtrollande skönhet och till den mystiske Isak, gårdens enstöring, vars familj en gång ägde marken. Men ju mer hon gräver i Älvkullens historia, desto närmare kommer hon den sorgliga sanningen – en sanning som hotar att dra henne in i en tragedi som fortfarande ekar bland blommorna.', 159);

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price) VALUES ('Astrid Skoog', 'Det som var', '1912', 'Lind Förlag', 'Svenska', 'Klassiker', 'Pocket', 'När den åldrade prästen Johannes återvänder till sin barndomsby efter många års frånvaro, är det som om tiden har stannat. Men under ytan bubblar gamla oförrätter och outtalade sanningar som vägrar att glömmas. I den grånande prästgården bor fortfarande hans syster Agnes, som aldrig lämnat byn och som vårdar minnen lika ömt som hon vårdar rosorna i trädgården. När Johannes börjar undersöka vad som egentligen hände den där sommaren då deras bror försvann spårlöst, tvingas han konfrontera sitt eget ansvar och den skuld han burit som en skugga genom livet.', 99);

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price) VALUES ('Anna Ström', 'En frånvarande sommar', '2017', 'Foré éditeur', 'Svenska', 'Samtida skönlitteratur', 'Pocket', 'När sommarens gassande sol sveper in över den sömniga byn Saint-Rémy-de-Provence, återvänder Léa från Paris för att tömma sin bortgångne fars lantvilla. Huset, med sina flagnande persienner och övervuxna trädgård, är fyllt av minnen från barndomens somrar – men också av outtalade hemligheter. När Léa möter Gabriel, en mystisk granne som tycks veta mer om hennes far än hon själv gör, börjar gamla brev och fotografier avslöja ett liv hon aldrig känt till. Medan cigarettröken stiger mot den heta provensalska natthimlen, tvingas Léa möta sanningen om sin fars förflutna och vad hon själv lämnat bakom sig. En frånvarande sommar är en känslostark roman om svek, försoning och vad som händer när det förflutna gör sig påmint.', 99);

INSERT INTO books (author, title, year, publisher, language, genre, format, description, price) VALUES ('Henrik Johansen', 'Hämnden', '2024', 'Norrlands Förlag', 'Svenska', 'Deckare', 'Inbunden', 'När åklagaren Nora Lindström återvänder till sin hemstad Göteborg efter flera år i Stockholm, möts hon av en stad i skräck. En rad brutala mord, alla med samma makabra signatur – ett ensamt spelkort placerat vid varje offer – skakar polisen. Offren visar sig ha kopplingar till en kontroversiell rättegång som Nora ledde för fem år sedan, ett fall som slutade med en frikännande dom. Medan antalet döda stiger och pressen ökar, börjar Nora inse att hon själv kan vara nästa måltavla. Hämnden är en psykologisk thriller om skuld, rättvisa och vad som händer när det förflutna vägrar släppa taget.', 189);
